### ISSUE TITLE
Implement fragment generation

### ISSUE THREAD

**Issue by nghi01** [zimmermatt/ob-winterm24-p2p#17]

**Comment by nghi01** [comment]
We decided to use Turtle to generate image fragments, should be relatively simple to generate coordinates within the range from 0 - width and 0 - height multiple times and then use these coordinates as Pixels to be colored (black, red, any color). The fragments will just be a list of coordinates that Contributor Artist can send over to Originator Artist for merging the fragments and generating the canvas and converting to PNG themselves. And then from [this thread](https://stackoverflow.com/questions/35629520/convert-images-drawn-by-turtle-to-png-in-python), we can technically try to use ghostscript and then automate the conversion to PNG using the subprocess module.

**Comment by nghi01** [comment]
Actually, from our researching, Pillow will directly be able to generate the png file, which might be a better option to generate fragments.

**Comment by yen-mai-codes** [comment]
- Update fragment generation to sign the completed fragment with the originator’s public key
