### ISSUE TITLE
Create script to initiate multiple nodes listening for requests

### ISSUE THREAD

**Issue by nghi01** [zimmermatt/ob-winterm24-p2p#3]
Spin up nodes on different ports listening for requests via UDPServer

**Comment by zimmermatt** [comment]
We had talked about putting this in a `bin` directory at the root of the project. Thinking about it further, I'm thinking it makes sense to have a `devops` directory at the root (so a peer directory to `src`). This will provide some organization for supporting scripts and tools for devops considerations.

A script like this would go in `devops/deploy`. Additional support scripts for the build beyond the main `Makefile` would go in `devops/build`.

**Comment by nghi01** [comment]
That sounds good. I've relocated the script on the pull request accordingly
